//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WA_Chamba
{
    using System;
    using System.Collections.Generic;
    
    public partial class comentario
    {
        public int idcomentario { get; set; }
        public int idpersona { get; set; }
        public int idDetalleServicio { get; set; }
        public string titulo { get; set; }
        public string contenido { get; set; }
        public decimal likes { get; set; }
        public decimal dislikes { get; set; }
    
        public virtual detalleServicio detalleServicio { get; set; }
        public virtual persona persona { get; set; }
    }
}
