//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WA_Chamba
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentoValidacion
    {
        public int idDocumentoValidacion { get; set; }
        public int idpersona { get; set; }
        public int idDocumento { get; set; }
        public string estadoDocumento { get; set; }
    
        public virtual documento documento { get; set; }
        public virtual persona persona { get; set; }
    }
}
