//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WA_Chamba
{
    using System;
    using System.Collections.Generic;
    
    public partial class imagen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public imagen()
        {
            this.detalleServicio = new HashSet<detalleServicio>();
        }
    
        public int idimagen { get; set; }
        public string ruta { get; set; }
        public string extencion { get; set; }
        public Nullable<int> tamaño { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleServicio> detalleServicio { get; set; }
    }
}
