//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WA_Chamba
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public persona()
        {
            this.comentario = new HashSet<comentario>();
            this.detalleServicio = new HashSet<detalleServicio>();
            this.documentoValidacion = new HashSet<documentoValidacion>();
        }
    
        public int idpersona { get; set; }
        public string idDistrito { get; set; }
        public string nombres { get; set; }
        public string apePaterno { get; set; }
        public string apeMaterno { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string sexo { get; set; }
        public string dni { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public string imagenPerfil { get; set; }
        public int idtipoCuenta { get; set; }
        public string nom_usuario { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> fechaRegistrado { get; set; }
        public string estadoCuenta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comentario> comentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleServicio> detalleServicio { get; set; }
        public virtual distrito distrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentoValidacion> documentoValidacion { get; set; }
        public virtual tipoCuenta tipoCuenta { get; set; }
    }
}
